### ISSUE TITLE
Error while executing the script to modify tempdb files

### ISSUE THREAD

**Issue by vkappa1** [imajaydwivedi/Space-Capacity-Automation#10]
@imajaydwivedi 

In the first place this script is really awesome and safe. Couldn't imagine the work behind developing this. almost of the features are working as expected and posting below to let you know the issue I have faced. Also attached the screen shot of Verbose 

After executing the function 
EXEC tempdb..[usp_AnalyzeSpaceCapacity] @expandTempDBSize = 1 ,@output4IdealScenario = 1

I get error "Arithmetic overflow error for data type tinyint, value = -3.". unable to solve this in the code. May you please help here to come out if it. 
![tempdb space calc issue_ verbose_output_1](https://user-images.githubusercontent.com/38454526/38854639-aa2722ca-4210-11e8-8c40-982b453ae2bb.png)
![tempdb space calc issue_1](https://user-images.githubusercontent.com/38454526/38854644-ac342d4c-4210-11e8-8e97-8d9f0fb8b82e.png)

**Comment by imajaydwivedi** [comment]
Thanks @vkappa1 for logging this issue. 

Issue has been resolved. I have modified the procedure to resolve the bug. Kindly take the latest update, and verify that version should be **3.6.2**.

![image](https://user-images.githubusercontent.com/18259277/38884144-4d29862c-428c-11e8-809d-52e811adcd62.png)

## Resolution Steps Taken:-
Variable **@_counts_of_Files_To_Be_Created** was declared as TINYINT. It was getting negative with logic (@_counts_of_Files_To_Be_Created = @_logicalCores - @_fileCounts).

In your case, @_logicalCores = 4, @_fileCount = 7, Means @_counts_of_Files_To_Be_Created = 4-7 = -3

Any variable of TINYINT data type accepts only positive value upto 255.

HINT:- Arithmetic Overflow always means data being put is _**Out of Range**_

.

**Comment by vkappa1** [comment]
Hey Scripting Guy!! Thanks man it worked. Kudos!! to your scripting knowledge.

**Comment by vkappa1** [comment]
Ajay 

Another query.. When I try to add files in drive which has more than 60GB free space I cannot. but my business asks to do so. please let me know what parameter to add to overcome this error?

"Log file for [XXXXXX] and [tempdb] databases is not being created since @oldVolume 'E:\Logs\' has more than 60 gb of free space.	*/"

**Comment by imajaydwivedi** [comment]
Kindly check parameter @allowMultiVolumeUnrestrictedFiles. I am not sure though.

**Comment by vkappa1** [comment]
Hello Ajay,

If there are no files in newly created drive it is not displaying the drive at all when I execute EXEC [dbo].[usp_AnalyzeSpaceCapacity]. May you fix this please.

Thanks
Anil
